# Generated by Django 4.2.4 on 2023-09-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('music_file', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(max_length=255)),
                ('studio', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('review_score', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField()),
                ('box_art_url', models.URLField()),
                ('box_art', models.BinaryField()),
                ('system', models.CharField(choices=[('GB', 'Gameboy'), ('GBC', 'Gameboy Color')], default='GB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
            ],
        ),
    ]
